--
-- **************************
-- ** APPLICATION DATABASE **
-- **************************
--

-- Paolo De Stefani 01.2025

-- This script MUST be executed by postgres user or a postgres like user
-- Connected to a database ("postgres" database is OK)

---------------------------------
-- APPLICATION DB ARCHITECTURE --
---------------------------------

-- * one database {pyAppPgDataBase}
-- * one role that own the database {pyAppPgOwnerRole} without login privilege
-- * one login role {pyAppPgLoginRole} that inherit {pyAppPgOwnerRole} privileges

-- Every database has 4 schemas:
-- * system     for system objects
-- * common     for common objects that are shared with all companies
-- * company    for objects associated with a company
-- * temp       for temporary tables

-- This set of variables will be be resolved before executing the scripts:
-- {pyAppPgOwnerRole}           = PostgresSQL Role that own all db objects without login privilege
-- {pyAppPgDataBase}            = Postgres database name
-- {pyAppPgLoginRole}           = PostgresSQL Role used for standard login users
-- {pyAppPgLoginPassword}       = Password for pyAppPgLoginRole
-- {pyAppName}                  = Python application name
-- {pyAppDescription}           = Python application description
-- {pyAppVersionMajor}          = Application version major number
-- {pyAppVersionMinor}          = Application version minor number
-- {pyAppVersionPatch}          = Application version patch number
-- {pyAppVersionTag}            = Application version tag
-- {pyAppVersionDescription}    = Application version description
-- {pyAppPgDataBaseTS}          = Database table space (MUST be created before script execution)
-- {pyAppPgTablesTS}            = Tables table space (MUST be created before script execution)
-- {pyAppPgIndexesTS}           = Indexes table space (MUST be created before script execution)


---------------------------
-- SYSTEM SCHEMA OBJECTS --
---------------------------

SET search_path = system;


-- system tables: itemview, sortfilter and report adaptations
CREATE TABLE adaptation (
    created_at              timestamptz(3) NOT NULL,
	created_by              text NOT NULL,
    updated_at              timestamptz(3) NOT NULL,
	updated_by              text NOT NULL,
    object_version          integer NOT NULL,
    --
    adaptation_id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    type                    char(1) NOT NULL, -- I: itemview, S: sortfilter, R: report
    class                   varchar(48) NOT NULL,
    description             text NOT NULL,
    class_sorting           integer NOT NULL DEFAULT 0,
    is_default_for_class    boolean NOT NULL DEFAULT false,
    report_id               BIGINT, -- only for report adaptation, reference to report definition
    row_count_limit         integer, -- only for sortfilter adaptation, limit the number of rows returned by the query, null means no limit
    is_system_object        boolean NOT NULL DEFAULT false,
    --
    CONSTRAINT adaptation_pk 
        PRIMARY KEY (adaptation_id) 
        USING INDEX TABLESPACE {pyAppPgIndexesTS},
	CONSTRAINT adaptation_unique 
        UNIQUE (type, class, description)
)
TABLESPACE {pyAppPgTablesTS};
COMMENT ON TABLE adaptation IS 
    'Itemview, sortfilter and report adaptations';
ALTER TABLE adaptation 
    OWNER TO {pyAppPgOwnerRole};

CREATE TRIGGER t99_update_company_user_date
    BEFORE INSERT OR UPDATE ON adaptation
    FOR EACH ROW EXECUTE PROCEDURE update_company_user_date();


-- system tables: adaptation settings
CREATE TABLE adaptation_setting (
    created_at              timestamptz(3) NOT NULL,
	created_by              text NOT NULL,
    updated_at              timestamptz(3) NOT NULL,
	updated_by              text NOT NULL,
    object_version          integer NOT NULL,
    --
    adaptation_setting_id   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    adaptation_id           BIGINT,
    -- for itemview adaptation
    column_number           integer,
    sorting                 integer,
    is_visible              boolean,
    size                    integer,
    -- for sortfilter and report adaptation
    element_type            char,
    layout_row              integer,
    combo1_index            integer,
	negate_state            boolean,
    combo2_index            integer,
	widget_value            text,
	--
    CONSTRAINT adaptation_setting_pk 
        PRIMARY KEY (adaptation_setting_id) 
        USING INDEX TABLESPACE {pyAppPgIndexesTS},
    CONSTRAINT adaptation_setting_adaptation_fk 
        FOREIGN KEY (adaptation_id) 
        REFERENCES adaptation (adaptation_id) 
        MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE
)
TABLESPACE {pyAppPgTablesTS};
COMMENT ON TABLE adaptation_setting IS 
    'Adaptation customizations settings';
ALTER TABLE adaptation_setting 
    OWNER TO {pyAppPgOwnerRole};

CREATE TRIGGER t99_update_company_user_date
    BEFORE INSERT OR UPDATE ON adaptation_setting 
    FOR EACH ROW EXECUTE PROCEDURE update_company_user_date();


--
-- system tables: sortfilter default for user
--
DROP TABLE IF EXISTS system.adaptation_user_default CASCADE;
CREATE TABLE system.adaptation_user_default (
    created_at                  timestamptz(3) NOT NULL,
	created_by                  text NOT NULL,
    updated_at                  timestamptz(3) NOT NULL,
	updated_by                  text NOT NULL,
    object_version              integer NOT NULL,
    --
	adaptation_user_default_id  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    adaptation_id               integer,
	app_user_code               varchar(48),
    --
    CONSTRAINT adaptation_user_default_pk 
        PRIMARY KEY (adaptation_user_default_id) 
        USING INDEX TABLESPACE {pyAppPgIndexesTS},
	CONSTRAINT adaptation_user_default_adaptation_fk 
        FOREIGN KEY (adaptation_id) 
        REFERENCES system.adaptation (adaptation_id)
		MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE,
	CONSTRAINT adaptation_user_default_app_user_fk
        FOREIGN KEY (app_user_code) 
        REFERENCES system.app_user (user_code)
		MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE
)
TABLESPACE {pyAppPgTablesTS};
COMMENT ON TABLE adaptation_user_default IS 
    'Adaptation default for user';
ALTER TABLE adaptation_user_default 
    OWNER TO {pyAppPgOwnerRole};

CREATE TRIGGER t99_update_company_user_date_trg 
    BEFORE INSERT OR UPDATE ON adaptation_user_default 
    FOR EACH ROW EXECUTE PROCEDURE update_company_user_date();
